const { Router } = require("express");
const userRouter = require("./user.router");
const regisRouter = require("./register.router");
const categoryRouter = require("./category.router");
const movieRouter = require("./movieRouter");
const loginRouter = require("./auth.router");
const subscriptionRouter = require("./subscription.router");
const subsUserRouter = require("./subsUser.router");
const router = Router();
router.get("/", (req, res) => {
  res.json("Welcome Home");
});
router.use(loginRouter);
router.use(userRouter);
router.use(regisRouter);
router.use(categoryRouter);
router.use(subscriptionRouter);
router.use(subsUserRouter);
// router.use(filmRouter);
router.use(movieRouter);
module.exports = router;
